# data
data_dir: data/MIMIC
data_name: MIMIC
min_vocab_freq: 3
max_seq_length: 2500

# train
seed: 0
epochs: 50
batch_size: 8
optimizer: adam
learning_rate: 0.001
weight_decay: 0
patience: 10
shuffle: true

# eval
eval_batch_size: 1
monitor_metrics: ['Micro-F1', 'Macro-F1', 'P@8', 'P@15', 'RP@8', 'RP@15']
val_metric: RP@15

# model
model_name: BiGRU
network_config:
  dropout: 0.2
  dropout2: 0.
  rnn_dim: 512
  rnn_layers: 1

# pretrained vocab / embeddings
vocab_file: data/MIMIC/vocab.csv
embed_file: data/MIMIC/processed_full.embed
normalize_embed: true
